spring.application.name=ThucTapProject

# Common configuration (shared across profiles)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# If no profile is specified, run with 'dev' settings by default.
spring.profiles.default=dev
